name: thlaby2_save_editor
description: A save editor for the game Touhou Labyrinth 2.

publish_to: 'none'

version: 0.5.1

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  file_picker: ^9.0.1
  flutter:
    sdk: flutter
  tfields:
    git:
      url: https://github.com/thurler/tfields
      ref: 1.0.0
  url_launcher: ^6.3.1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - img/character/
    - img/
