name: Build test version

on:
  push:
    branches:
      - 'development'

jobs:
  build-windows:
    name: Windows Native Build
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Flutter Environment
        uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: '3.7.12'

      - name: Flutter Config
        run: flutter config --enable-windows-desktop --no-analytics

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Flutter Build Windows Native
        run: flutter build windows --release

      - name: Archive Artifact
        uses: actions/upload-artifact@v3
        with:
          name: thlaby2-save-editor-windows
          path: build/windows/runner/Release/*

  build-linux:
    name: Linux Native Build
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update -y
          sudo apt install -y clang cmake curl libgtk-3-dev ninja-build pkg-config unzip xvfb

      - name: Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12'
          cache: true
          cache-key: 'flutter-3-7-12-linux'
          cache-path: ${{ runner.tool_cache }}/flutter/linux-3-7-12

      - name: Flutter Config
        run: flutter config --enable-linux-desktop --no-analytics

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Flutter Build Linux Native
        run: flutter build linux --release

      - name: Archive Artifact
        uses: actions/upload-artifact@v3
        with:
          name: thlaby2-save-editor-linux
          path: build/linux/x64/release/bundle/*
